- hosts: nodeonly
  connection: local
  gather_facts: yes
  roles:
    - pacman
    - git
    - aur
    - bash
    - golang
    - alacritty
    - docker
    - iosevka_font
    - miniforge
    - nvim
    - rustup
    - virt_manager
    - zig
