---
pacman_packages:
  - amd-ucode
  - alacritty
  - aws-cli
  - base-devel
  - cheese
  - clang
  - cmake
  - cuda
  - cups
  - curl
  - discord
  - docker
  - docker-buildx
  - docker-compose
  - drawio-desktop
  - gcc
  - gimp
  - htop
  - jq
  - libreoffice
  - libguestfs
  - minikube
  - ninja
  - nitrogen
  - noto-fonts
  - npm
  - numlockx
  - nvidia
  - nvidia-utils
  - obs-studio
  - obsidian
  - openbsd-netcat
  - pavucontrol
  - python-lxml
  - python-lsp-server
  - python-pip
  - qemu-full
  - reflector
  - steam
  - spotify-launcher
  - sqlite
  - tmux
  - ttf-dejavu
  - ttf-freefont
  - ttf-ubuntu-font-family
  - vde2
  - virt-manager
  - virt-viewer
  - vlc
  - wget
  - xorg
  - xorg-apps
  - xorg-server
  - xorg-xinit
...
